import { images } from "../../../constants/images";

export const DB = {
    data: [
        {
          id: 5814966241,
          title: "New items",
          cards: [
            {
              id: 5814966201,
              title: "LIMO",
              img: images.LIMO,
              discounts: "-10% for promo",
              isSelected: true,
            },
            {
              id: 5814966202,
              title: "SpiritBar",
              img: images.SPIRITBAR,
              discounts: "Set free",
              isSelected: false,
            },
          ],
        },
        {
          id: 5814126241,
          title: "Food and Drinks",
          cards: [
            {
              id: 5814966203,
              title: "EMBARGO Coctail Bar",
              img: images.EMBARGO,
              discounts: "-10%",
              isSelected: false,
            },
            {
              id: 5814966204,
              title: "SpiritBar",
              img: images.SPIRITBAR,
              discounts: "Set free",
              isSelected: false,
            },
            {
              id: 5814966205,
              title: "Myata",
              img: images.MYATA,
              discounts: "-20% on hookahs",
              isSelected: true,
            },
            {
              id: 5814966206,
              title: "Domino's Pizza",
              img: images.DOMINOS,
              discounts: "-25%",
              isSelected: false,
            },
            {
              id: 5814966207,
              title: "Papa John's",
              img: images.PAPAJOHNS,
              discounts: "-15%",
              isSelected: false,
            },
            {
              id: 5814966208,
              title: "Dodo Pizza",
              img: images.DODO,
              discounts: "-20%",
              isSelected: false,
            },
            {
              id: 5814966209,
              title: "Gadzila",
              img: images.GADZILA,
              discounts: "-10%",
              isSelected: false,
            },
          ],
        },
        {
          id: 5811366241,
          title: "Health",
          cards: [
            {
              id: 5814966210,
              title: "EVO welness club",
              img: images.EVO,
              discounts: "-20%",
              isSelected: false,
            },
            {
              id: 5814966211,
              title: "VOKA microsurgery center",
              img: images.VOKA,
              discounts: "-10%",
              isSelected: true,
            },
          ],
        },
        {
          id: 5814216241,
          title: "Education and hobbies",
          cards: [
            {
              id: 5814966212,
              title: "Foreign language courses SKYENG English, German...",
              img: images.SKYENG,
              discounts: "up to -45%",
              isSelected: false,
            },
            {
              id: 5814966213,
              title: "Skandilab",
              img: images.SKANDILAB,
              discounts: "-12%",
              isSelected: false,
            },
            {
              id: 5814966214,
              title: "ROBOLAB School of Robotics",
              img: images.ROBOLAB,
              discounts: "-10%",
              isSelected: false,
            },
            {
              id: 5814966215,
              title: "Musical school",
              img: null,
              discounts: "-10%",
              isSelected: images.MUSICALSCHOOL,
            },
            {
              id: 5814966216,
              title: "FASOL musical rocking chair",
              img: images.FASOL,
              discounts: "-30%",
              isSelected: false,
            },
            {
              id: 5814966217,
              title: "Online Class",
              img: images.ONLNE_SCHOOL,
              discounts: "-7%",
              isSelected: false,
            },
          ],
        },
        {
          id: 5814964941,
          title: "Beauty",
          cards: [],
        },
        {
          id: 5814911241,
          title: "Sports",
          cards: [],
        },
        {
          id: 5813466241,
          title: "Clothing",
          cards: [],
        },
        {
          id: 5814966561,
          title: "Services",
          cards: [],
        },
      ],
      categoryList: [
        { id: 0, name: "All discounts", isSelected: true },
        { id: 1, name: "New items", isSelected: false },
        { id: 2, name: "Health", isSelected: false },
        { id: 3, name: "Education and hobbies", isSelected: false },
        { id: 4, name: "Food and Drinks", isSelected: false },
        { id: 5, name: "Sports", isSelected: false },
        { id: 6, name: "Clothing", isSelected: false },
        { id: 7, name: "Services", isSelected: false },
      ],
      favoritesData: [],
      currentCategory: "All discounts",
}